# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Ubuntu latest build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: vcpkg build
      uses: johnwason/vcpkg-action@v6
      id: vcpkg
      with:
        pkgs: gtest fmt spdlog
        triplet: x64-linux
        token: ${{ github.token }}
        github-binarycache: true
          
    - name: Configure & Build
      run: cmake --workflow --preset LinuxWorkflow
